[package]
name = "concurrent"
version = "0.1.0"
edition = "2024"

[dependencies]
layout-rs = "0.1.3"
pest = { version = "2.8.3", features = ["miette-error"] }
pest_derive = "2.8.3"
petgraph = "0.8.3"
svg2pdf = "0.13.0"
